/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/assets/{asset_id}/download': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Download */
    get: operations['download_api_assets__asset_id__download_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/assets/{asset_id}/stream': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Stream */
    get: operations['stream_api_assets__asset_id__stream_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/backup': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create Backup */
    post: operations['create_backup_api_backup_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/browse/series': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Browse Series */
    get: operations['browse_series_api_browse_series_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/catalog': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Catalog */
    get: operations['catalog_api_catalog_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/collections': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Collections */
    get: operations['collections_api_collections_get'];
    put?: never;
    /** Create Collection */
    post: operations['create_collection_api_collections_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/collections/{collection_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Edit Collection */
    patch: operations['edit_collection_api_collections__collection_id__patch'];
    trace?: never;
  };
  '/api/collections/{collection_id}/entries': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Change Collection */
    post: operations['change_collection_api_collections__collection_id__entries_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/collections/{collection_id}/works': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Collection Works */
    get: operations['collection_works_api_collections__collection_id__works_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/export': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Export */
    get: operations['export_api_export_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/home/collections': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Collection Next */
    get: operations['collection_next_api_home_collections_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/home/continue': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Continue List */
    get: operations['continue_list_api_home_continue_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/home/next': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Next Followed */
    get: operations['next_followed_api_home_next_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/import': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Import Book */
    post: operations['import_book_api_import_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Login */
    post: operations['login_api_login_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Logout */
    post: operations['logout_api_logout_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/openapi.json': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Schema */
    get: operations['schema_api_openapi_json_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/operations': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Operations */
    get: operations['operations_api_operations_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/operations/preview': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Preview Group */
    post: operations['preview_group_api_operations_preview_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/operations/{operation_id}/commit': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Commit Group */
    post: operations['commit_group_api_operations__operation_id__commit_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/operations/{operation_id}/undo': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Undo Group */
    post: operations['undo_group_api_operations__operation_id__undo_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/representations/{representation_id}/cover': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Cover */
    get: operations['cover_api_representations__representation_id__cover_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/representations/{representation_id}/playback': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Playback */
    get: operations['playback_api_representations__representation_id__playback_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/representations/{representation_id}/progress': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Progress */
    patch: operations['progress_api_representations__representation_id__progress_patch'];
    trace?: never;
  };
  '/api/series': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Series */
    get: operations['series_api_series_get'];
    put?: never;
    /** Create Series */
    post: operations['create_series_api_series_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/series/{series_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Series */
    get: operations['get_series_api_series__series_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Edit Series */
    patch: operations['edit_series_api_series__series_id__patch'];
    trace?: never;
  };
  '/api/series/{series_id}/following': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Follow Series */
    patch: operations['follow_series_api_series__series_id__following_patch'];
    trace?: never;
  };
  '/api/series/{series_id}/works': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Series Works */
    get: operations['series_works_api_series__series_id__works_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/session': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Session */
    get: operations['session_api_session_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/status': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Status */
    get: operations['status_api_status_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/works/{work_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Work */
    get: operations['work_api_works__work_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Edit */
    patch: operations['edit_api_works__work_id__patch'];
    trace?: never;
  };
  '/api/works/{work_id}/personal': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Personal */
    patch: operations['personal_api_works__work_id__personal_patch'];
    trace?: never;
  };
  '/api/works/{work_id}/records': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Records */
    get: operations['records_api_works__work_id__records_get'];
    put?: never;
    /** Add Record */
    post: operations['add_record_api_works__work_id__records_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/works/{work_id}/records/{record_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Remove Record */
    delete: operations['remove_record_api_works__work_id__records__record_id__delete'];
    options?: never;
    head?: never;
    /** Edit Record */
    patch: operations['edit_record_api_works__work_id__records__record_id__patch'];
    trace?: never;
  };
  '/health/live': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Live */
    get: operations['live_health_live_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/health/ready': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Ready */
    get: operations['ready_health_ready_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** AssetOut */
    AssetOut: {
      /** Id */
      id: string;
      /** Original Name */
      original_name: string;
      /** Sha256 */
      sha256: string;
      /** Size */
      size: number;
    };
    /** AudioTrackOut */
    AudioTrackOut: {
      /** Asset Id */
      asset_id: string;
      /** Chapters */
      chapters: components['schemas']['ChapterOut'][];
      /** Duration */
      duration: number;
      /** Original Name */
      original_name: string;
      /** Title */
      title: string;
    };
    /** CatalogPage */
    CatalogPage: {
      /** Items */
      items: components['schemas']['WorkOut'][];
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
      /** Total */
      total: number;
    };
    /** ChapterOut */
    ChapterOut: {
      /** Start */
      start: number;
      /** Title */
      title: string;
    };
    /** CollectionChange */
    CollectionChange: {
      /**
       * Action
       * @enum {string}
       */
      action: 'add' | 'remove' | 'up' | 'down' | 'add_series';
      /** Revision */
      revision: number;
      /** Series Id */
      series_id?: string | null;
      /** Work Id */
      work_id?: string | null;
    };
    /** CollectionEdit */
    CollectionEdit: {
      /**
       * Home
       * @default false
       */
      home: boolean;
      /** Name */
      name: string;
      /**
       * Revision
       * @default 1
       */
      revision: number;
    };
    /** CollectionEntryOut */
    CollectionEntryOut: {
      /** Finished */
      finished: boolean;
      /** Id */
      id: string;
      /** Position */
      position: number;
      work: components['schemas']['WorkOut'];
    };
    /** CollectionNextOut */
    CollectionNextOut: {
      collection: components['schemas']['CollectionOut'];
      work: components['schemas']['WorkOut'];
    };
    /** CollectionNextPage */
    CollectionNextPage: {
      /** Items */
      items: components['schemas']['CollectionNextOut'][];
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
      /** Total */
      total: number;
    };
    /** CollectionOut */
    CollectionOut: {
      /** Count */
      count: number;
      /**
       * Home
       * @default false
       */
      home: boolean;
      /** Id */
      id: string;
      /** Name */
      name: string;
      /**
       * Revision
       * @default 1
       */
      revision: number;
    };
    /** CollectionPage */
    CollectionPage: {
      /** Items */
      items: components['schemas']['CollectionOut'][];
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
      /** Total */
      total: number;
    };
    /** CollectionWorksPage */
    CollectionWorksPage: {
      collection: components['schemas']['CollectionOut'];
      /** Items */
      items: components['schemas']['CollectionEntryOut'][];
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
      /** Total */
      total: number;
    };
    /** ConflictOut */
    ConflictOut: {
      /** Field */
      field: string;
      /** Source */
      source: string;
      /** Target */
      target: string;
    };
    /** ContinueOut */
    ContinueOut: {
      progress: components['schemas']['ProgressOut'];
      /** Representation Id */
      representation_id: string;
      work: components['schemas']['WorkOut'];
    };
    /** ContinuePage */
    ContinuePage: {
      /** Items */
      items: components['schemas']['ContinueOut'][];
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
      /** Total */
      total: number;
    };
    /** EditionEdit */
    EditionEdit: {
      /**
       * Abridgement
       * @default unknown
       * @enum {string}
       */
      abridgement: 'unknown' | 'unabridged' | 'abridged';
      /** Id */
      id: string;
      /** Identifier */
      identifier: string;
      /** Language */
      language: string;
      /**
       * Narrator
       * @default
       */
      narrator: string;
      /** Publisher */
      publisher: string;
    };
    /** EditionOut */
    EditionOut: {
      /** Abridgement */
      abridgement: string;
      /** Id */
      id: string;
      /** Identifier */
      identifier: string;
      /** Language */
      language: string;
      /** Medium */
      medium: string;
      /** Narrator */
      narrator: string;
      /** Publisher */
      publisher: string;
      /** Representations */
      representations: components['schemas']['RepresentationOut'][];
    };
    /** FollowEdit */
    FollowEdit: {
      /** Following */
      following: boolean;
      /** Revision */
      revision: number;
    };
    /** GroupCommit */
    GroupCommit: {
      /** Resolutions */
      resolutions?: {
        [key: string]: 'source' | 'target';
      };
    };
    /** GroupPreview */
    GroupPreview: {
      /** Conflicts */
      conflicts: components['schemas']['ConflictOut'][];
      /** Explanation */
      explanation: string;
      /** Id */
      id: string;
      /** Mode */
      mode: string;
      source: components['schemas']['WorkOut'];
      target: components['schemas']['WorkOut'] | null;
    };
    /** GroupRequest */
    GroupRequest: {
      /**
       * Mode
       * @enum {string}
       */
      mode: 'editions' | 'representation' | 'split';
      /** Representation Id */
      representation_id?: string | null;
      /** Source Work Id */
      source_work_id: string;
      /** Target Edition Id */
      target_edition_id?: string | null;
      /** Target Work Id */
      target_work_id?: string | null;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][];
    };
    /** ImportResult */
    ImportResult: {
      /** Duplicate */
      duplicate: boolean;
      work: components['schemas']['WorkOut'];
    };
    /** Login */
    Login: {
      /** Password */
      password: string;
    };
    /** MembershipEdit */
    MembershipEdit: {
      /**
       * Designation
       * @default
       */
      designation: string;
      /** Position */
      position: number;
      /** Series Id */
      series_id: string;
    };
    /** MembershipOut */
    MembershipOut: {
      /**
       * Designation
       * @default
       */
      designation: string;
      /** Position */
      position: number;
      series: components['schemas']['SeriesOut'];
      /** Series Id */
      series_id: string;
    };
    /** NextOut */
    NextOut: {
      /** Designation */
      designation: string;
      series: components['schemas']['SeriesOut'];
      work: components['schemas']['WorkOut'];
    };
    /** NextPage */
    NextPage: {
      /** Items */
      items: components['schemas']['NextOut'][];
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
      /** Total */
      total: number;
    };
    /** OperationOut */
    OperationOut: {
      /** Created At */
      created_at: string;
      /** Id */
      id: string;
      /** State */
      state: string;
      /** Work Ids */
      work_ids: string[];
    };
    /** OperationPage */
    OperationPage: {
      /** Items */
      items: components['schemas']['OperationOut'][];
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
      /** Total */
      total: number;
    };
    /** PersonalEdit */
    PersonalEdit: {
      /**
       * Notes
       * @default
       */
      notes: string;
      /** Rating */
      rating?: number | null;
      /** Revision */
      revision: number;
      /** Shelf Override */
      shelf_override?: ('library' | 'archive') | null;
      /** Tags */
      tags?: string[];
    };
    /** PersonalOut */
    PersonalOut: {
      /**
       * Default Shelf
       * @default library
       * @enum {string}
       */
      default_shelf: 'library' | 'archive';
      /**
       * Notes
       * @default
       */
      notes: string;
      /** Rating */
      rating?: number | null;
      /**
       * Shelf
       * @default library
       * @enum {string}
       */
      shelf: 'library' | 'archive';
      /** Shelf Override */
      shelf_override?: ('library' | 'archive') | null;
      /** Tags */
      tags?: string[];
    };
    /** PlaybackOut */
    PlaybackOut: {
      progress: components['schemas']['ProgressOut'];
      /** Representation Id */
      representation_id: string;
      /** Title */
      title: string;
      /** Tracks */
      tracks: components['schemas']['AudioTrackOut'][];
      /** Work Id */
      work_id: string;
    };
    /** ProgressEdit */
    ProgressEdit: {
      /** Asset Id */
      asset_id: string;
      /**
       * Completed
       * @default false
       */
      completed: boolean;
      /** Position */
      position: number;
      /** Revision */
      revision: number;
      /**
       * Speed
       * @default 1
       */
      speed: number;
    };
    /** ProgressOut */
    ProgressOut: {
      /** Asset Id */
      asset_id: string;
      /**
       * Completed
       * @default false
       */
      completed: boolean;
      /** Position */
      position: number;
      /** Representation Id */
      representation_id: string;
      /** Revision */
      revision: number;
      /**
       * Speed
       * @default 1
       */
      speed: number;
      /** Updated At */
      updated_at: string | null;
    };
    /** RecordEdit */
    RecordEdit: {
      /** Finished */
      finished?: string | null;
      /**
       * Kind
       * @enum {string}
       */
      kind: 'read' | 'listen';
      /** Representation Id */
      representation_id?: string | null;
      /**
       * Revision
       * @default 1
       */
      revision: number;
      /**
       * Started
       * Format: date
       */
      started: string;
    };
    /** RecordOut */
    RecordOut: {
      /** Created At */
      created_at: string;
      /** Finished */
      finished?: string | null;
      /** Id */
      id: string;
      /**
       * Kind
       * @enum {string}
       */
      kind: 'read' | 'listen';
      /** Representation Id */
      representation_id?: string | null;
      /**
       * Revision
       * @default 1
       */
      revision: number;
      /**
       * Started
       * Format: date
       */
      started: string;
      /** Work Id */
      work_id: string;
    };
    /** RecordPage */
    RecordPage: {
      /** Items */
      items: components['schemas']['RecordOut'][];
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
      /** Total */
      total: number;
    };
    /** RepresentationOut */
    RepresentationOut: {
      /** Assets */
      assets: components['schemas']['AssetOut'][];
      /** Capabilities */
      capabilities: string[];
      /** Facts */
      facts: {
        [key: string]: unknown;
      };
      /** Format */
      format: string;
      /** Has Cover */
      has_cover: boolean;
      /** Id */
      id: string;
    };
    /** RunOut */
    RunOut: {
      /** Finished */
      finished: number;
      /** Owned */
      owned: number;
      series: components['schemas']['SeriesOut'];
    };
    /** RunPage */
    RunPage: {
      /** Items */
      items: components['schemas']['RunOut'][];
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
      /** Total */
      total: number;
    };
    /** RunWorksPage */
    RunWorksPage: {
      /** Finished Work Ids */
      finished_work_ids: string[];
      /** Items */
      items: components['schemas']['WorkOut'][];
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
      /** Total */
      total: number;
    };
    /** SeriesEdit */
    SeriesEdit: {
      /** Name */
      name: string;
      /**
       * Revision
       * @default 1
       */
      revision: number;
      /**
       * Run
       * @default
       */
      run: string;
    };
    /** SeriesOut */
    SeriesOut: {
      /** Following */
      following: boolean;
      /** Id */
      id: string;
      /** Name */
      name: string;
      /**
       * Revision
       * @default 1
       */
      revision: number;
      /**
       * Run
       * @default
       */
      run: string;
    };
    /** SeriesPage */
    SeriesPage: {
      /** Items */
      items: components['schemas']['SeriesOut'][];
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
      /** Total */
      total: number;
    };
    /** StatusOut */
    StatusOut: {
      /** Books */
      books: number;
      /** Import Errors */
      import_errors: number;
      /**
       * Version
       * @default 0.1.0
       */
      version: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>;
      /** Input */
      input?: unknown;
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
    /** WorkEdit */
    WorkEdit: {
      /** Authors */
      authors: string[];
      /** Description */
      description: string;
      /** Editions */
      editions?: components['schemas']['EditionEdit'][] | null;
      /** Memberships */
      memberships?: components['schemas']['MembershipEdit'][] | null;
      /** Revision */
      revision: number;
      /** Title */
      title: string;
    };
    /** WorkOut */
    WorkOut: {
      /** Authors */
      authors: string[];
      /** Created At */
      created_at: string;
      /** Description */
      description: string;
      /** Editions */
      editions: components['schemas']['EditionOut'][];
      /** Id */
      id: string;
      /** Memberships */
      memberships: components['schemas']['MembershipOut'][];
      personal: components['schemas']['PersonalOut'];
      /** Revision */
      revision: number;
      /** Title */
      title: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  download_api_assets__asset_id__download_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        asset_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  stream_api_assets__asset_id__stream_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        asset_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  create_backup_api_backup_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  browse_series_api_browse_series_get: {
    parameters: {
      query?: {
        q?: string;
        scope?: 'all' | 'library' | 'archive';
        medium?: ('ebook' | 'comic' | 'audio') | null;
        following?: boolean;
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RunPage'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  catalog_api_catalog_get: {
    parameters: {
      query?: {
        q?: string;
        limit?: number;
        offset?: number;
        scope?: 'all' | 'library' | 'archive';
        medium?: ('ebook' | 'comic' | 'audio') | null;
        unassigned?: boolean;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CatalogPage'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  collections_api_collections_get: {
    parameters: {
      query?: {
        q?: string;
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CollectionPage'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  create_collection_api_collections_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CollectionEdit'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CollectionOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  edit_collection_api_collections__collection_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        collection_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CollectionEdit'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CollectionOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  change_collection_api_collections__collection_id__entries_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        collection_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CollectionChange'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CollectionOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  collection_works_api_collections__collection_id__works_get: {
    parameters: {
      query?: {
        limit?: number;
        offset?: number;
      };
      header?: never;
      path: {
        collection_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CollectionWorksPage'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  export_api_export_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  collection_next_api_home_collections_get: {
    parameters: {
      query?: {
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CollectionNextPage'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  continue_list_api_home_continue_get: {
    parameters: {
      query?: {
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ContinuePage'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  next_followed_api_home_next_get: {
    parameters: {
      query?: {
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['NextPage'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  import_book_api_import_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/octet-stream': string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ImportResult'];
        };
      };
    };
  };
  login_api_login_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['Login'];
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  logout_api_logout_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  schema_api_openapi_json_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  operations_api_operations_get: {
    parameters: {
      query?: {
        work_id?: string | null;
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OperationPage'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  preview_group_api_operations_preview_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['GroupRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['GroupPreview'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  commit_group_api_operations__operation_id__commit_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        operation_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['GroupCommit'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OperationOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  undo_group_api_operations__operation_id__undo_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        operation_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OperationOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  cover_api_representations__representation_id__cover_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        representation_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  playback_api_representations__representation_id__playback_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        representation_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PlaybackOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  progress_api_representations__representation_id__progress_patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        representation_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ProgressEdit'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProgressOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  series_api_series_get: {
    parameters: {
      query?: {
        q?: string;
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SeriesPage'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  create_series_api_series_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SeriesEdit'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SeriesOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_series_api_series__series_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        series_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SeriesOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  edit_series_api_series__series_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        series_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SeriesEdit'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SeriesOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  follow_series_api_series__series_id__following_patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        series_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['FollowEdit'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SeriesOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  series_works_api_series__series_id__works_get: {
    parameters: {
      query?: {
        limit?: number;
        offset?: number;
        scope?: 'all' | 'library' | 'archive';
        medium?: ('ebook' | 'comic' | 'audio') | null;
      };
      header?: never;
      path: {
        series_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RunWorksPage'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  session_api_session_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  status_api_status_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['StatusOut'];
        };
      };
    };
  };
  work_api_works__work_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        work_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['WorkOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  edit_api_works__work_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        work_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['WorkEdit'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['WorkOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  personal_api_works__work_id__personal_patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        work_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['PersonalEdit'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['WorkOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  records_api_works__work_id__records_get: {
    parameters: {
      query?: {
        limit?: number;
        offset?: number;
      };
      header?: never;
      path: {
        work_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RecordPage'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  add_record_api_works__work_id__records_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        work_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RecordEdit'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RecordOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  remove_record_api_works__work_id__records__record_id__delete: {
    parameters: {
      query: {
        revision: number;
      };
      header?: never;
      path: {
        work_id: string;
        record_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  edit_record_api_works__work_id__records__record_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        work_id: string;
        record_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RecordEdit'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RecordOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  live_health_live_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  ready_health_ready_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
}
