/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/assets/{asset_id}/download': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Download */
    get: operations['download_api_assets__asset_id__download_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/assets/{asset_id}/stream': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Stream */
    get: operations['stream_api_assets__asset_id__stream_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/backup': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create Backup */
    post: operations['create_backup_api_backup_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/catalog': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Catalog */
    get: operations['catalog_api_catalog_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/export': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Export */
    get: operations['export_api_export_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/home/continue': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Continue List */
    get: operations['continue_list_api_home_continue_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/import': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Import Book */
    post: operations['import_book_api_import_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Login */
    post: operations['login_api_login_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Logout */
    post: operations['logout_api_logout_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/openapi.json': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Schema */
    get: operations['schema_api_openapi_json_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/operations': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Operations */
    get: operations['operations_api_operations_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/operations/preview': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Preview Group */
    post: operations['preview_group_api_operations_preview_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/operations/{operation_id}/commit': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Commit Group */
    post: operations['commit_group_api_operations__operation_id__commit_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/operations/{operation_id}/undo': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Undo Group */
    post: operations['undo_group_api_operations__operation_id__undo_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/representations/{representation_id}/cover': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Cover */
    get: operations['cover_api_representations__representation_id__cover_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/representations/{representation_id}/playback': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Playback */
    get: operations['playback_api_representations__representation_id__playback_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/representations/{representation_id}/progress': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Progress */
    patch: operations['progress_api_representations__representation_id__progress_patch'];
    trace?: never;
  };
  '/api/series': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Series */
    get: operations['series_api_series_get'];
    put?: never;
    /** Create Series */
    post: operations['create_series_api_series_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/series/{series_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Edit Series */
    patch: operations['edit_series_api_series__series_id__patch'];
    trace?: never;
  };
  '/api/series/{series_id}/works': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Series Works */
    get: operations['series_works_api_series__series_id__works_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/session': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Session */
    get: operations['session_api_session_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/status': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Status */
    get: operations['status_api_status_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/works/{work_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Work */
    get: operations['work_api_works__work_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Edit */
    patch: operations['edit_api_works__work_id__patch'];
    trace?: never;
  };
  '/health/live': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Live */
    get: operations['live_health_live_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/health/ready': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Ready */
    get: operations['ready_health_ready_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** AssetOut */
    AssetOut: {
      /** Id */
      id: string;
      /** Original Name */
      original_name: string;
      /** Sha256 */
      sha256: string;
      /** Size */
      size: number;
    };
    /** AudioTrackOut */
    AudioTrackOut: {
      /** Asset Id */
      asset_id: string;
      /** Chapters */
      chapters: components['schemas']['ChapterOut'][];
      /** Duration */
      duration: number;
      /** Original Name */
      original_name: string;
      /** Title */
      title: string;
    };
    /** CatalogPage */
    CatalogPage: {
      /** Items */
      items: components['schemas']['WorkOut'][];
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
      /** Total */
      total: number;
    };
    /** ChapterOut */
    ChapterOut: {
      /** Start */
      start: number;
      /** Title */
      title: string;
    };
    /** ConflictOut */
    ConflictOut: {
      /** Field */
      field: string;
      /** Source */
      source: string;
      /** Target */
      target: string;
    };
    /** ContinueOut */
    ContinueOut: {
      progress: components['schemas']['ProgressOut'];
      /** Representation Id */
      representation_id: string;
      work: components['schemas']['WorkOut'];
    };
    /** ContinuePage */
    ContinuePage: {
      /** Items */
      items: components['schemas']['ContinueOut'][];
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
      /** Total */
      total: number;
    };
    /** EditionEdit */
    EditionEdit: {
      /**
       * Abridgement
       * @default unknown
       * @enum {string}
       */
      abridgement: 'unknown' | 'unabridged' | 'abridged';
      /** Id */
      id: string;
      /** Identifier */
      identifier: string;
      /** Language */
      language: string;
      /**
       * Narrator
       * @default
       */
      narrator: string;
      /** Publisher */
      publisher: string;
    };
    /** EditionOut */
    EditionOut: {
      /** Abridgement */
      abridgement: string;
      /** Id */
      id: string;
      /** Identifier */
      identifier: string;
      /** Language */
      language: string;
      /** Medium */
      medium: string;
      /** Narrator */
      narrator: string;
      /** Publisher */
      publisher: string;
      /** Representations */
      representations: components['schemas']['RepresentationOut'][];
    };
    /** GroupCommit */
    GroupCommit: {
      /** Resolutions */
      resolutions?: {
        [key: string]: 'source' | 'target';
      };
    };
    /** GroupPreview */
    GroupPreview: {
      /** Conflicts */
      conflicts: components['schemas']['ConflictOut'][];
      /** Explanation */
      explanation: string;
      /** Id */
      id: string;
      /** Mode */
      mode: string;
      source: components['schemas']['WorkOut'];
      target: components['schemas']['WorkOut'] | null;
    };
    /** GroupRequest */
    GroupRequest: {
      /**
       * Mode
       * @enum {string}
       */
      mode: 'editions' | 'representation' | 'split';
      /** Representation Id */
      representation_id?: string | null;
      /** Source Work Id */
      source_work_id: string;
      /** Target Edition Id */
      target_edition_id?: string | null;
      /** Target Work Id */
      target_work_id?: string | null;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][];
    };
    /** ImportResult */
    ImportResult: {
      /** Duplicate */
      duplicate: boolean;
      work: components['schemas']['WorkOut'];
    };
    /** Login */
    Login: {
      /** Password */
      password: string;
    };
    /** MembershipEdit */
    MembershipEdit: {
      /**
       * Designation
       * @default
       */
      designation: string;
      /** Position */
      position: number;
      /** Series Id */
      series_id: string;
    };
    /** MembershipOut */
    MembershipOut: {
      /**
       * Designation
       * @default
       */
      designation: string;
      /** Position */
      position: number;
      series: components['schemas']['SeriesOut'];
      /** Series Id */
      series_id: string;
    };
    /** OperationOut */
    OperationOut: {
      /** Created At */
      created_at: string;
      /** Id */
      id: string;
      /** State */
      state: string;
      /** Work Ids */
      work_ids: string[];
    };
    /** OperationPage */
    OperationPage: {
      /** Items */
      items: components['schemas']['OperationOut'][];
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
      /** Total */
      total: number;
    };
    /** PlaybackOut */
    PlaybackOut: {
      progress: components['schemas']['ProgressOut'];
      /** Representation Id */
      representation_id: string;
      /** Title */
      title: string;
      /** Tracks */
      tracks: components['schemas']['AudioTrackOut'][];
      /** Work Id */
      work_id: string;
    };
    /** ProgressEdit */
    ProgressEdit: {
      /** Asset Id */
      asset_id: string;
      /**
       * Completed
       * @default false
       */
      completed: boolean;
      /** Position */
      position: number;
      /** Revision */
      revision: number;
      /**
       * Speed
       * @default 1
       */
      speed: number;
    };
    /** ProgressOut */
    ProgressOut: {
      /** Asset Id */
      asset_id: string;
      /**
       * Completed
       * @default false
       */
      completed: boolean;
      /** Position */
      position: number;
      /** Representation Id */
      representation_id: string;
      /** Revision */
      revision: number;
      /**
       * Speed
       * @default 1
       */
      speed: number;
      /** Updated At */
      updated_at: string | null;
    };
    /** RepresentationOut */
    RepresentationOut: {
      /** Assets */
      assets: components['schemas']['AssetOut'][];
      /** Capabilities */
      capabilities: string[];
      /** Facts */
      facts: {
        [key: string]: unknown;
      };
      /** Format */
      format: string;
      /** Has Cover */
      has_cover: boolean;
      /** Id */
      id: string;
    };
    /** SeriesEdit */
    SeriesEdit: {
      /** Name */
      name: string;
      /**
       * Revision
       * @default 1
       */
      revision: number;
      /**
       * Run
       * @default
       */
      run: string;
    };
    /** SeriesOut */
    SeriesOut: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      /**
       * Revision
       * @default 1
       */
      revision: number;
      /**
       * Run
       * @default
       */
      run: string;
    };
    /** SeriesPage */
    SeriesPage: {
      /** Items */
      items: components['schemas']['SeriesOut'][];
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
      /** Total */
      total: number;
    };
    /** StatusOut */
    StatusOut: {
      /** Books */
      books: number;
      /** Import Errors */
      import_errors: number;
      /**
       * Version
       * @default 0.1.0
       */
      version: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>;
      /** Input */
      input?: unknown;
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
    /** WorkEdit */
    WorkEdit: {
      /** Authors */
      authors: string[];
      /** Description */
      description: string;
      /** Editions */
      editions?: components['schemas']['EditionEdit'][] | null;
      /** Memberships */
      memberships?: components['schemas']['MembershipEdit'][] | null;
      /** Revision */
      revision: number;
      /** Title */
      title: string;
    };
    /** WorkOut */
    WorkOut: {
      /** Authors */
      authors: string[];
      /** Created At */
      created_at: string;
      /** Description */
      description: string;
      /** Editions */
      editions: components['schemas']['EditionOut'][];
      /** Id */
      id: string;
      /** Memberships */
      memberships: components['schemas']['MembershipOut'][];
      /** Revision */
      revision: number;
      /** Title */
      title: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  download_api_assets__asset_id__download_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        asset_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  stream_api_assets__asset_id__stream_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        asset_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  create_backup_api_backup_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  catalog_api_catalog_get: {
    parameters: {
      query?: {
        q?: string;
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CatalogPage'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  export_api_export_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  continue_list_api_home_continue_get: {
    parameters: {
      query?: {
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ContinuePage'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  import_book_api_import_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/octet-stream': string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ImportResult'];
        };
      };
    };
  };
  login_api_login_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['Login'];
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  logout_api_logout_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  schema_api_openapi_json_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  operations_api_operations_get: {
    parameters: {
      query?: {
        work_id?: string | null;
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OperationPage'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  preview_group_api_operations_preview_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['GroupRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['GroupPreview'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  commit_group_api_operations__operation_id__commit_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        operation_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['GroupCommit'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OperationOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  undo_group_api_operations__operation_id__undo_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        operation_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OperationOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  cover_api_representations__representation_id__cover_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        representation_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  playback_api_representations__representation_id__playback_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        representation_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PlaybackOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  progress_api_representations__representation_id__progress_patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        representation_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ProgressEdit'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProgressOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  series_api_series_get: {
    parameters: {
      query?: {
        q?: string;
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SeriesPage'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  create_series_api_series_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SeriesEdit'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SeriesOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  edit_series_api_series__series_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        series_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SeriesEdit'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SeriesOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  series_works_api_series__series_id__works_get: {
    parameters: {
      query?: {
        limit?: number;
        offset?: number;
      };
      header?: never;
      path: {
        series_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CatalogPage'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  session_api_session_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  status_api_status_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['StatusOut'];
        };
      };
    };
  };
  work_api_works__work_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        work_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['WorkOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  edit_api_works__work_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        work_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['WorkEdit'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['WorkOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  live_health_live_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  ready_health_ready_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
}
